language: node_js
node_js:
- '5.11'

deploy:
- provider: s3
  access_key_id: AKIAJ2KIL275BGG3NOJQ
  secret_access_key: &1
    secure: LqxGRZ7b55k1rcPvrp8SRiR7JPOt9v8y6HdEtcRTWB01Rg+I/P3hYNBGhUIXZdB9KNC3Gw+46IxSovOnqQC4AdUlxxo0PDTpa1huC4aux1aftKsrj2El4edKT4kexfCdmo7548MZw7/+33emCvRbaw9g7ErNma31IL0Kx47chmbGLeODhPXbxyhiA3anlpiGavLHbC7/shEm1SQn6Aok9Wtmnk7nUz5u6efUPQHQtiUPimx4/aUN2fqYvAvOu1NVPFdm3BCNvuiWsn4rpIIZKQPou9kvzlLwFr8XnWW8QGzNqpKJUF9mVQBRZ1XILqg0qs7J572SQcerL00rAJ6NXnttBqcf+eugIQBZ6ZOL/HAm+VEJGMmfV06y3ZFY21Ag7pD710NYSPQWK68wLIjBYSpm8lNHnlMIHpOo/kH7UWCKaJtGRoMnRSkyBhgaQE1A3+bsk4D+k9QnG/H41bDE16+xLyh9OKWsLOlaha+XxzYIIF5DwcDz29ujRDts/8kSjpAWCTHtTDwgORedQvcQX6JmxSMipjXm1eoDHdwMzJ+p4vBBoUH52w6+zwrPI9Fs26gfBbEzTX8BXSE52fDtOmz/IVF6hC41HiN0u0yhsJ4tWUpVkZlozxuLlENh1daGJJi+L8xMPbLwWjIFuho5WCXznAPbp8DGodsbbx4FW3A=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  wait-until-deployed: true
  region: eu-west-1
  on: &2
    repo: jordanegiuly/trello-hooks
  bucket: trello-hooks/zips
- provider: codedeploy
  access_key_id: AKIAJ2KIL275BGG3NOJQ
  secret_access_key: *1
  bucket: trello-hooks/zips
  key: trello-hooks.zip
  bundle_type: zip
  application: TrelloHooks
  deployment_group: TrelloHooks
  region: eu-west-1
  wait-until-deployed: true
  on: *2
before_deploy:
- scripts/pre-deploy.sh
